# Site settings
author: literal-block-0957
title: 
header-img: img/home-bg.png
email: amdarvin14@gmail.com
copyright_name: literal-block-0957
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  adarvin14

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
